# Project information
site_name: A Beginner's Guide to Docker
site_author: Ananya Gupta
site_description: A Beginner's Guide to Docker

# Repository
repo_name: Ananya2003Gupta/Beginners-Guide-to-Docker
repo_url: https://github.com/Ananya2003Gupta/Beginners-Guide-to-Docker

# Copyright
copyright: Copyright &copy; 2024 Ananya Gupta

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - navigation.indexes
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: sky
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: white
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'


#Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ananya2003Gupta
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ananyagupta05/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iamananyagupta_

nav:
  - Home:
    - Overview: index.md 
    - Table of Contents: Content.md
    - Introduction:
      - 1. Introduction to Docker: Introduction/index.md
      - 1.1  What is Docker: Introduction/WhatIsDocker.md
      - 1.2  Advantages of Using Docker: Introduction/AdvantagesOfUsingDocker.md
      - 1.3  Docker Architecture: Introduction/DockerArchitecture.md
      - 1.4  Running A Blogging Platform: Introduction/RunningABloggingPlatform.md
    - Getting Started with Docker:
      - 2. Getting Started with Docker: GettingStartedWithDocker/index.md
      - 2.1  Installing Docker: GettingStartedWithDocker/InstallingDocker.md
      - 2.2  Docker Editions and Versions: GettingStartedWithDocker/DockerEditionsAndVersions.md
      - 2.3  Running the First Docker Container: GettingStartedWithDocker/RunningTheFirstDockerContainer.md
    - Docker Images:
      - 3. Docker Images: DockerImages/index.md
      - 3.1  Understanding Docker Images: DockerImages/UnderstandingDockerImages.md
      - 3.2  Docker Hub and Official Repositories: DockerImages/DockerHubAndOfficialRepositories.md
      - 3.3  Building Custom Docker Images: DockerImages/BuildingCustomDockerImages.md
      - 3.4  Working with Dockerfiles: DockerImages/WorkingWithDockerfile.md
    - Docker Containers:
      - 4. Docker Containers: DockerContainers/index.md
      - 4.1  Understanding Docker Containers: DockerContainers/UnderstandingDockerContainers.md
      - 4.2  Container Lifecycle Management: DockerContainers/ContainerLifecycleManagement.md
      - 4.3  Container Networking: DockerContainers/ContainerNetworking.md
      - 4.4  Container Data Management: DockerContainers/ContainerDataManagement.md 
    - Docker Volumes:
      - 5. Docker Volumes: DockerVolumes/index.md
      - 5.1  Understanding Docker Volumes: DockerVolumes/UnderstandingDockerVolumes.md
      - 5.2  Persistent Data Storage in Containers: DockerVolumes/PersistentDataStorageInContainers.md
      - 5.3  Managing Data with Named Volumes and Bind Mounts: DockerVolumes/NamedVolumesAndBindMounts.md
    - Docker Compose:
      - 6. Docker Compose: DockerCompose/index.md
      - 6.1 Introduction to Docker Compose: DockerCompose/IntroductionToDockerCompose.md
      - 6.2 Defining Multicontainer Applications with Docker Compose: DockerCompose/MulticontainerApplicationsWithYaml.md
      - 6.3 Running and Managing Multicontainer Setups: DockerCompose/RunningAndManagingMultiContainerSetups.md
    - Docker Networking:
      - 7. Docker Networking: DockerNetworking/index.md
      - 7.1 Overview of Docker Networking: DockerNetworking/OverviewofDockerNetworking.md
      - 7.2 Bridge Networks: DockerNetworking/BridgeNetworksInDocker.md
      - 7.3 Container Communication and Linking: DockerNetworking/ContainerCommunicationAndLinkingInDocker.md
      - 7.4 Custom Network Creation: DockerNetworking/CustomNetworkCreationInDocker.md
    - Docker Swarm:
      - 8. Docker Swarm: DockerSwarm/index.md
      - 8.1 Introduction to Docker Swarm: DockerSwarm/IntroductionToDockerSwarm.md
      - 8.2 Setting Up a Swarm Cluster: DockerSwarm/SettingUpSwarmCluster.md
      - 8.3 Deploying and Managing Services in a Swarm: DockerSwarm/ServicesInSwarm.md
    - Docker Security:
      - 9. Docker Security: DockerSecurity/index.md
      - 9.1 Container Isolation and Security: DockerSecurity/ContainerIsolationAndSecurity.md
      - 9.2 Best Practices for Securing Docker Deployments: DockerSecurity/SecuringDockerDeployments.md
      - 9.3 Security Container Images: DockerSecurity/SecuringContainerImages.md
    - Docker Tips and Tricks:
      - 10. Docker Tips and Tricks: DockerTipsandTricks/index.md
      - 10.1 Useful Docker Commands: DockerTipsandTricks/UsefulDockerCommands.md
      - 10.2 Debugging Containers: DockerTipsandTricks/DebuggingContainers.md
      - 10.3 Working with Docker on Diffrent Platforms: DockerTipsandTricks/WorkingWithDocker.md
    - Docker Ecosystem:
      - 11. Docker Ecosystem: DockerEcosystem/index.md
      - 11.1 Docker Ecosystem Overview: DockerEcosystem/DockerEcosystemOverview.md
      - 11.2 Integration with Kubernetes: DockerEcosystem/IntegrationWithKubernetes.md
    - Conclusion:
      - 12. Conclusion: Conclusion/index.md
      - 12.1 Summary of Key Concepts: Conclusion/SummaryOfKeyConcepts.md
      - 12.2 Further Learning Resources: Conclusion/FurtherLearningResources.md
      - 12.3 References: Conclusion/References.md
